### ISSUE TITLE
level 3 upper chest causes crash

### ISSUE THREAD

**Issue by Teklar223** [HolyTrie/Dark-Times-In-Sherwood#114]
could be all chests, null is being invoked.
Error:
Invoking error handler due to
RuntimeError: indirect call to null
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[58892]:0x10d11e5
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[58512]:0x10b7292
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[63425]:0x1172d47
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[64305]:0x118469a
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[89833]:0x1f21ac3
invoke_iiii@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.framework.js:10:408419
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[64289]:0x1183731
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[1145]:0xd9bd1
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[89089]:0x1ed952b
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[85922]:0x1e54bdf
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[85420]:0x1e28f6b
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[66259]:0x1290409
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[87980]:0x1e7c62f
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[58565]:0x10b985d
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[58886]:0x10d0f39
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[58887]:0x10d0fd5
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[58871]:0x10d079f
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[8966]:0x3a09d6
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[89836]:0x1f21ae7
invoke_viii@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.framework.js:10:409053
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[52800]:0xf852ae
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[23103]:0x763f05
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[23062]:0x76147e
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[89839]:0x1f21b13
invoke_viiiiii@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.framework.js:10:411023
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[23033]:0x75f968
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[23088]:0x7634fc
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[89841]:0x1f21b35
invoke_viiii@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.framework.js:10:409341
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[23083]:0x7628de
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[23082]:0x761f65
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[90161]:0x1f23815
invoke_viidiji@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.framework.js:10:423428
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[21940]:0x718193
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[21937]:0x717bc9
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[21962]:0x71ddfe
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[89842]:0x1f21b47
invoke_iiiiii@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.framework.js:10:408883
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[21960]:0x71d24b
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[89841]:0x1f21b35
invoke_viiii@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.framework.js:10:409341
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[21349]:0x6eda5a
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[20653]:0x6d8981
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[63441]:0x117309b
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[64305]:0x118469a
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[89833]:0x1f21ac3
invoke_iiii@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.framework.js:10:408419
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[64289]:0x1183731
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[1145]:0xd9bd1
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[89089]:0x1ed952b
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[85921]:0x1e54b67
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[77189]:0x18cae5d
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[77195]:0x18cb09e
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[65956]:0x126631b
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[65956]:0x126638f
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[89810]:0x1f0cde6
@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.wasm:wasm-function[89838]:0x1f21aff
browserIterationFunc@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.framework.js:10:225205
callUserCallback@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.framework.js:10:178774
runIter@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.framework.js:10:180030
Browser_mainLoop_runner@https://html-classic.itch.zone/html/9938599/Dark-Times-In-SherwoodV7/Build/Dark-Times-In-SherwoodV7.framework.js:10:178310 Dark-Times-In-SherwoodV7.loader.js:1:3922

**Comment by Teklar223** [comment]
don't know if related
![image](https://github.com/HolyTrie/Dark-Times-In-Sherwood/assets/73063105/82c894ae-3aac-4048-9844-c41892f048f8)

**Comment by 20shaked20** [comment]
POP UP Text for the chests are not valid, need to add/ modify

**Comment by 20shaked20** [comment]
fixed
