### ISSUE TITLE
Main menu bugs and options

### ISSUE THREAD

**Issue by Teklar223** [HolyTrie/Dark-Times-In-Sherwood#117]
Bugs:
1. freeze when returning to main menu and pressing play again

Enhancements:
1. Credits
2. Quit Game

**Comment by 20shaked20** [comment]
main menu - wont fix, i have a way to fix it, but its not that clean, and i think its ok to let the player press "resume controls"

**Comment by 20shaked20** [comment]
Bugs: 
FIXED! fucking dumb ass unity, was resseting the Time.timescale to 0 after load/reset scene.
so simply had to add 
Time.timescale = 1f;
to the method in gamemanger..

**Comment by 20shaked20** [comment]
Extra - Added scene selection :D

**Comment by 20shaked20** [comment]
done
