### ISSUE TITLE
sticky walking-talking

### ISSUE THREAD

**Issue by OmriPer** [HolyTrie/Dark-Times-In-Sherwood#32]
when Pressing e to talk with an npc, if a walk button (a,d) is already pressed then the walking doesn't stop until the end of the dialogue.
![image](https://github.com/HolyTrie/Dark-Times-In-Sherwood/assets/115950996/3bbf36ca-0356-455d-90e1-f01f851fa36a)

**Comment by 20shaked20** [comment]
Thanks! we will approach that
