### ISSUE TITLE
תקיעה+ כתב לא הכי ברור+ מתקפה חדשה שלא הוסברה בהתחלה 

### ISSUE THREAD

**Issue by ohadtaizi** [HolyTrie/Dark-Times-In-Sherwood#33]
ביקורת על המשחק נתקעתי בקיר שלא הצלחתי לעבור אותו אחרי 3 דקות משחק 
הכתב של הוראות לא הכי ברור , יש הוראה ללחוץ על 5 שנראה כמו S .
שיחקתי עם המקשים פתאום יצא לי חץ וקשת לא הצלחתי לשחזר את זה .

**Comment by 20shaked20** [comment]
We will approach the "S" = "5" situation,  Thanks! 
for further testing follow the tutorial as its intended, if you did, you'd see later that there is a Key mapped to "F" that tells to switch weapons 👍🏽

**Comment by Teklar223** [comment]
consider editing the pixelart to have a strong curve to highlight that S =/= 5
