### ISSUE TITLE
אנימציית אוייב נתקעת

### ISSUE THREAD

**Issue by HadarBitan** [HolyTrie/Dark-Times-In-Sherwood#34]
כאשר לשחקן נגמר החיים האנימציה של האויב קצת נתקעת כשהוא במקום של השחקן.

**Comment by HadarBitan** [comment]
כאשר לשחקן נגמר החיים האנימציה של האויב קצת נתקעת כשהוא במקום של השחקן.

**Comment by 20shaked20** [comment]
as of now, it's suppose to be like that .
it considers the player "dead".
but we do not allow the player to die today. 
thanks for pointing it out

**Comment by 20shaked20** [comment]
Fixed - simply added Death state to player which now will not cause this
