### ISSUE TITLE
מעבר בין חרב לקשת לא ברור + יכולת לא מוסברת + לא מצליח להיכנס לבאר

### ISSUE THREAD

**Issue by Maor-Or** [HolyTrie/Dark-Times-In-Sherwood#35]
לא הצלחתי להבין מה קורה כאשר אני לוחץ על G והדמות שלי נהיית סגולה, בנוסף כאשר אני לוחץ על F אז הנשק משתנה בין קשת לחרב, וזה לא היה מוסבר בשום מקום
בנוסף, משום מה לא הצלחתי לרדת למטה לתוך הבאר, למרות שכתוב שצריך לרדת למטה

**Comment by Teklar223** [comment]
tutorial message is old, its S+Space (this is the main issue here), as when you go down the well the weapon shift mechanic is explained.
