### ISSUE TITLE
מינימאפ קטן + קיר חוסם שניתן לתקוף דרכו + קפיצה לפעמים לא עובדת

### ISSUE THREAD

**Issue by EliGreenblatt** [HolyTrie/Dark-Times-In-Sherwood#37]
מינימאפ קטן , יש קיר שאי אפשר לעבור דרכו אבל כן להרוג וקפיצה למטה לפעמים לא עובד לי

**Comment by Teklar223** [comment]
Please provide an image or a way to reproduce the wall relate issue.
if you could also explain what you mean by small Minimap that would be great (for example, is the size itself good, but the camera is too zoomed out?)

**Comment by Teklar223** [comment]
I think these are the 'gates' in the first scene which cant be opened, but guards are still placed next to them.

the first location is the first entrance to the mansion which is blocked.
the second location is the two gates with guards inside that are located directly to the right of the player when leaving the well (or directly left from the door to the next stage)
