### ISSUE TITLE
השחקן שתוקף לא מוריד חיים לשחקן שלי

### ISSUE THREAD

**Issue by ofekrotem** [HolyTrie/Dark-Times-In-Sherwood#39]
![image](https://github.com/HolyTrie/Dark-Times-In-Sherwood/assets/92383710/29a9f035-3194-4e82-ba51-bb89f01c9b3c)

**Comment by Teklar223** [comment]
this issue #36

**Comment by Teklar223** [comment]
Might be a separate issue from #36, needs more testing (i.e - even if the raycast attack hits, no hp is being lost anyway)

**Comment by 20shaked20** [comment]
Fixed, there was some raycasting issues with attack
