### ISSUE TITLE
when pressing on the s key nothing happens.

### ISSUE THREAD

**Issue by Noya-G** [HolyTrie/Dark-Times-In-Sherwood#44]
<img width="1680" alt="Screenshot 2024-03-06 at 13 35 58" src="https://github.com/HolyTrie/Dark-Times-In-Sherwood/assets/73538626/d025428f-6104-403f-8fa6-b58f7dd22d56">
<img width="1680" alt="Screenshot 2024-03-06 at 13 36 40" src="https://github.com/HolyTrie/Dark-Times-In-Sherwood/assets/73538626/b885e457-b90a-496b-9694-6dcf56971e7a">

when pressing on the s key nothing happens.
when reaching the wall it is not clear to the player how you need to pass the wall.

**Comment by 20shaked20** [comment]
Yup it a UI Fix we needed to do - SPACE + S to go down, we forgot to change that.
Thanks! 💯
