### ISSUE TITLE
קפיצה קדימה + תקיפה

### ISSUE THREAD

**Issue by Dorshir** [HolyTrie/Dark-Times-In-Sherwood#45]
כשקופצים בתנועה קדימה ומנסים לתקוף, התקיפה עוצרת את התנועה קדימה. קצת לא מסתדר לטעמי, פחות זורם.

**Comment by 20shaked20** [comment]
Fixed that a bit - > still need to fine tune a bit.

**Comment by 20shaked20** [comment]
issue is fixed - player can move and attack simultaneity, also improved it a bit- there's a sequential attack that the player enters if he keeps holding the attack button.
