### ISSUE TITLE
הסבר נוסף למקשי המקלדת

### ISSUE THREAD

**Issue by liron02319** [HolyTrie/Dark-Times-In-Sherwood#47]
היי, אהבתי תמשחק !
רק הערה קטנה - בתחילת המשחק נתקלתי שהשחקן יכול לזוז ב A . D למרות שבד'כ אני רגיל לחצים ימין שמאל - כך ש''הופתעתי'' לגלות שאפשר גם לשחק איתם
יהיה נוח אם יהיה רשום שאפשר גם בהם או פשוט שיהיה בתחילת המשחק כמו HELP שיסבירו על מקשי המשחק הכלליים

**Comment by 20shaked20** [comment]
Thanks, will consider adding it to the game menu 💯

**Comment by Teklar223** [comment]
the game controls are designed around A and D, we should consider either adding a double binding for every control that is binded to keys close to the arrows, or remove the arrow controls entirely.

**Comment by Teklar223** [comment]
Alternatively, we could just add control rebinding as we aim to do it eventually anyway.

**Comment by 20shaked20** [comment]
Added HowToPlay section
