### ISSUE TITLE
מידע על מצב השחקן והאויב כתוצאה ממתקפה

### ISSUE THREAD

**Issue by EliGreenblatt** [HolyTrie/Dark-Times-In-Sherwood#49]
משחק יפה ומושך את העין אני אשמח ליותר visualization, כמה חיים יש לי? כמה חיים יש ליריב? אני בכלל פוגע בו כשאני תוקף? אני תוקף בלי להפסיק מי מנצח בקרב? זה דברים שאני לא מקבל עליהם מספיק מידע

**Comment by Teklar223** [comment]
these are in the game, maybe we should enlarge the HUD elements.

you are correct that there is no indication of being hit or hitting an enemy!
