### ISSUE TITLE
Level 2 - 3

### ISSUE THREAD

**Issue by 20shaked20** [HolyTrie/Dark-Times-In-Sherwood#68]
Streamline level 2-3 , to make level 2 (sherif location) more dialog based and less fighting/puzzles to in order to reach faster level 3 (where the boss and the core game mechanic happens)

**Comment by 20shaked20** [comment]
Level 2- pretty much done (only do something with second dialog option - fighting guards)

**Comment by Teklar223** [comment]
note to check traps in level 2 + add ghost puzzle to level 3
